services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
      - PYTHONHASHSEED=random
      - PIP_NO_CACHE_DIR=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
    restart: unless-stopped
